version: '3'
services:
  avxmngapp:
    container_name: avxmngapp
    image: avixy/maintenancesrv:0.1 # NOTE: Remember to update the version in each release
    build:
      context: .
      dockerfile: Dockerfile-production
    ports: 
      - "4567:4567" # Sinatra mapping
    depends_on: 
      - mongodb

  mongodb:
    container_name: mongodb
    image: mongo
