FROM ruby:2.4
WORKDIR /usr/src/app
COPY Gemfile /usr/src/app
COPY Gemfile.lock /usr/src/app
RUN gem install bundler
RUN bundle install
COPY . /usr/src/app
EXPOSE 4567
ENV RACK_ENV=production
CMD ["rackup", "-o", "0.0.0.0", "-p", "4567"]
