test:
  clients:
    default:
      database: mngsrv-test
      hosts:
       - mongodb:27017

development:
  clients:
    default:
      database: mngsrv-dev
      hosts:
       - localhost:27017

production:
  clients:
    default:
      database: mngsrv-production
      hosts:
       - mongodb:27017