development:
    clients:
        default:
            database: test
            hosts:
              - localhost:27017
            #options:
                #user: 'avixy'
                #password: 'avx3000'
                #server_selection_timeout: 1
