test:
  clients:
    default:
      database: mngsrv-test
      hosts:
       - 172.18.0.2:27017
  options:
    raise_not_found_error: false

development:
  clients:
    default:
      database: mngsrv-dev
      hosts:
       - localhost:27017
  options:
    raise_not_found_error: false

production:
  clients:
    default:
      database: mngsrv-production
      hosts:
       - 172.18.0.2:27017
  options:
    raise_not_found_error: false
