#!/bin/bash
rake todo
git add todo.txt

echo "=============================================="
echo "[WARNING] Todo list updated in file todo.txt !"
echo "=============================================="

